"""Tests for the Gaussian HMM regime classifier.

Uses synthetic 2-regime data generated by hand so we can verify the classifier
identifies the regimes correctly and labels them deterministically.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

pytest.importorskip("hmmlearn", reason="hmmlearn not installed")

from causal_portfolio.regimes.hmm import (
    RegimeClassifier,
    build_regime_features,
    dwell_stats,
)


def _synthetic_two_regime_features(n=600, seed=0) -> np.ndarray:
    """Two regimes: first half low-stress, second half high-stress."""
    rng = np.random.default_rng(seed)
    half = n // 2
    low = rng.normal(loc=[0.0, 0.0], scale=[0.3, 0.3], size=(half, 2))
    high = rng.normal(loc=[2.0, 2.0], scale=[0.5, 0.5], size=(n - half, 2))
    return np.vstack([low, high])


# ── deterministic state labeling ────────────────────────────────────


def test_state_zero_is_lower_stress():
    """The relabel step must always put the lower-mean state at index 0."""
    X = _synthetic_two_regime_features()
    cls = RegimeClassifier(n_states=2, random_state=42).fit(X)
    means = cls.state_means()
    # Feature 0 mean of state 0 must be < state 1
    assert means[0, 0] < means[1, 0]


def test_labels_match_regime_structure():
    X = _synthetic_two_regime_features(n=600)
    cls = RegimeClassifier(n_states=2, random_state=42).fit(X)
    labels = cls.decode(X)
    # First half should be mostly label 0 (low stress)
    assert (labels[:300] == 0).mean() > 0.85
    # Second half should be mostly label 1 (high stress)
    assert (labels[300:] == 1).mean() > 0.85


def test_decode_returns_correct_shape():
    X = _synthetic_two_regime_features(n=300)
    cls = RegimeClassifier(n_states=2, random_state=42).fit(X)
    labels = cls.decode(X)
    assert labels.shape == (300,)
    assert set(np.unique(labels).tolist()).issubset({0, 1})


# ── causal decode ───────────────────────────────────────────────────


def test_causal_decode_does_not_use_future():
    """predict_causal at t=k should only depend on data[:k+1]."""
    X = _synthetic_two_regime_features(n=200)
    cls = RegimeClassifier(n_states=2, random_state=42).fit(X)
    labels_full = cls.predict_causal(X)

    # Recompute by truncating: labels_full[t] should equal predict_causal(X[:t+1])[-1]
    for t in [10, 50, 100, 150]:
        truncated = cls.predict_causal(X[: t + 1])
        assert labels_full[t] == truncated[-1]


# ── error handling ──────────────────────────────────────────────────


def test_decode_before_fit_raises():
    cls = RegimeClassifier()
    with pytest.raises(RuntimeError, match="fit"):
        cls.decode(np.zeros((10, 2)))


def test_state_means_before_fit_raises():
    cls = RegimeClassifier()
    with pytest.raises(RuntimeError, match="fit"):
        cls.state_means()


def test_fit_rejects_1d_input():
    cls = RegimeClassifier()
    with pytest.raises(ValueError, match="2D"):
        cls.fit(np.array([1.0, 2.0, 3.0]))


# ── transition matrix ──────────────────────────────────────────────


def test_transition_matrix_rows_sum_to_one():
    X = _synthetic_two_regime_features()
    cls = RegimeClassifier(n_states=2, random_state=42).fit(X)
    T = cls.transition_matrix()
    assert T.shape == (2, 2)
    np.testing.assert_allclose(T.sum(axis=1), np.ones(2), atol=1e-6)


# ── feature builder ────────────────────────────────────────────────


def test_build_regime_features_zscores():
    rng = np.random.default_rng(0)
    idx = pd.date_range("2024-01-01", periods=200)
    # Use truly random returns so rolling vol actually varies
    returns = pd.DataFrame({"btc_return": rng.normal(0, 0.02, 200)}, index=idx)
    macro_full = pd.DataFrame({"vixcls": rng.uniform(15, 35, 200)}, index=idx)

    feats = build_regime_features(macro_full, returns, vol_window=21)
    assert set(feats.columns) == {"vix", "btc_vol"}
    for col in feats.columns:
        assert abs(feats[col].mean()) < 0.01, f"{col} not zero-mean: {feats[col].mean()}"
        assert abs(feats[col].std() - 1.0) < 0.05, f"{col} not unit-std: {feats[col].std()}"


def test_build_regime_features_missing_vixcls_raises():
    macro = pd.DataFrame({"dff": [5.0] * 10}, index=pd.date_range("2024", periods=10))
    returns = pd.DataFrame({"btc_return": [0.01] * 10},
                           index=pd.date_range("2024", periods=10))
    with pytest.raises(KeyError, match="vixcls"):
        build_regime_features(macro, returns)


# ── dwell stats ─────────────────────────────────────────────────────


def test_dwell_stats_simple():
    labels = np.array([0, 0, 0, 1, 1, 0, 0, 1])
    stats = dwell_stats(labels)
    assert stats[0]["days"] == 5
    assert stats[1]["days"] == 3
    assert stats[0]["n_runs"] == 2  # two separate stretches of 0
    assert stats[1]["n_runs"] == 2
    assert stats[0]["pct"] == 5 / 8


def test_dwell_stats_single_run():
    labels = np.array([0, 0, 0, 0])
    stats = dwell_stats(labels)
    assert stats[0]["n_runs"] == 1
    assert stats[0]["mean_run_length"] == 4
    assert 1 not in stats  # state 1 never appears


def test_dwell_stats_empty():
    assert dwell_stats(np.array([], dtype=int)) == {}


# ── multi-restart fit ──────────────────────────────────────────────


def test_multi_restart_picks_higher_likelihood():
    """With n_restarts > 1, fit() should pick the best-likelihood result."""
    X = _synthetic_two_regime_features(n=400)
    single = RegimeClassifier(n_states=2, random_state=42, n_restarts=1).fit(X)
    multi = RegimeClassifier(n_states=2, random_state=42, n_restarts=5).fit(X)

    # Multi-restart can only be >= single-start in likelihood
    from hmmlearn.hmm import GaussianHMM  # noqa
    single_ll = single._fitted.model.score(X)
    multi_ll = multi._fitted.model.score(X)
    assert multi_ll >= single_ll - 1e-6  # equal in this easy case is fine


# ── forward filter (causal posterior) ──────────────────────────────


def test_forward_filter_returns_valid_probabilities():
    X = _synthetic_two_regime_features(n=300)
    cls = RegimeClassifier(n_states=2, random_state=42).fit(X)
    post = cls.forward_filter(X)
    assert post.shape == (300, 2)
    # Each row sums to ~1
    np.testing.assert_allclose(post.sum(axis=1), np.ones(300), atol=1e-6)
    # All entries in [0, 1]
    assert (post >= 0).all() and (post <= 1).all()


def test_forward_filter_is_strictly_causal():
    """Forward posterior at t must not depend on data after t."""
    X = _synthetic_two_regime_features(n=200)
    cls = RegimeClassifier(n_states=2, random_state=42).fit(X)
    post_full = cls.forward_filter(X)

    # Truncating the input must give the same posterior at the truncation point
    for t in [50, 100, 150]:
        post_truncated = cls.forward_filter(X[: t + 1])
        np.testing.assert_allclose(post_full[t], post_truncated[-1], atol=1e-9)


def test_forward_filter_labels_align_with_decode_on_clean_data():
    """On well-separated regimes, forward filter and Viterbi should mostly agree."""
    X = _synthetic_two_regime_features(n=600)
    cls = RegimeClassifier(n_states=2, random_state=42).fit(X)
    forward_labels = cls.predict_forward(X)
    viterbi_labels = cls.decode(X)
    # Allow some disagreement at the very start (forward filter has less context)
    agreement = (forward_labels == viterbi_labels).mean()
    assert agreement > 0.90, f"Only {agreement:.2%} agreement"


# ── rolling fit + decode ──────────────────────────────────────────


def test_rolling_fit_decode_returns_proper_shape():
    from causal_portfolio.regimes.hmm import rolling_fit_decode

    rng = np.random.default_rng(0)
    idx = pd.date_range("2024-01-01", periods=400)
    feats = pd.DataFrame(
        rng.normal(size=(400, 2)), index=idx, columns=["vix", "btc_vol"],
    )
    labels = rolling_fit_decode(
        feats, window_size=100, refit_every=50, n_states=2, n_restarts=1,
    )
    assert len(labels) == 400
    # First window_size entries are NaN
    assert labels.iloc[:100].isna().all()
    # Rest are valid labels
    assert not labels.iloc[100:].isna().any()
    assert set(labels.iloc[100:].unique()).issubset({0, 1})


def test_rolling_fit_decode_short_input_returns_all_nan():
    from causal_portfolio.regimes.hmm import rolling_fit_decode

    idx = pd.date_range("2024-01-01", periods=50)
    feats = pd.DataFrame(np.zeros((50, 2)), index=idx, columns=["a", "b"])
    labels = rolling_fit_decode(feats, window_size=100, n_states=2)
    assert labels.isna().all()
